### ISSUE TITLE
Co nedela vyplneny autoruv Twitter a co by mohl delat.

### ISSUE THREAD

**Issue by lspdv** [pyvec/blog.python.cz#13]
Zda se, ze Twitter u autora nema zadne vyuziti. Autor pri vyplnovani jiste pomyslel na to, ze se nekde ctenar proklikem dozvi o vsech tech fantastickych vecech, ktere tweetoval.

"Nebylobylibyloby" od veci, kdyby tlaciko dole pod informacema o autorovi, ktere tweetuje clanek melo v textu tweetu tedy alespon zmineny @ na ucet autora :-)

**Comment by honzajavorek** [comment]
Myslím, že to tam bylo možná na to, aby si blog mohl vysosat tvůj Twitter obrázek, pokud nemáš Gravatar. Ale nerad bych kecal. Každopádně dobrý nápad!

**Comment by lspdv** [comment]
To zitra zkusim! Pripadne to dopisu do Readme

Dne pátek 30. prosince 2016 Honza Javorek <notifications@github.com>
napsal(a):

**Comment by lspdv** [comment]
honzajavorek tak to tak zatim nefunguje. Pokud nevyplnis Gravatar, tak i s vyplnenym Twitterem to stale hazi maluvku s lidmi z Pyva.

Ale mohl by to byt dobry studijni ukol pro me :-) zkusim vymyslet PR na danube-delta.

**Comment by honzajavorek** [comment]
Tak to hodně štěstí! danube-delta byl původně projekt pro osobní potřebu, ale snad je aspoň trochu udělaný tak, že by z něj šel udělat projekt, do kterého se dá přispívat... Budu se snažit být nápomocen :)

**Comment by frenzymadness** [comment]
Upravil jsem šablonu, otestoval na aktuální podobě blogu a vytvořil PR.

Pozor na to, že nejmladší článek s vyplněným twitterem je ten od @lspdv

**Comment by honzajavorek** [comment]
Je to venku: https://pypi.python.org/pypi/danube-delta/1.1.0
