### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by hroncok** [pyvec/blog.python.cz#51]
https://blog.python.cz/ works but all the links are http and there is mixed content, so the website looks disrupted.

**Comment by hroncok** [comment]
maybe https://github.com/pyvec/blog.python.cz/blob/77ffb9c63ea0f3b2ea334196b6dec64e13a149f9/settings.py#L23

**Comment by messa** [comment]
Or `SITEURL = '//blog.python.cz'`

**Comment by encukou** [comment]
Nastaveno (#54); http://blog.python.cz přesměrovává na HTTPS.
