### ISSUE TITLE
Co nezapomenout dát do listopadového článku

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/blog.python.cz#6]
- Start kurzu PyLadies v Ostravě
- Nová podoba Pyva v Ostravě

**Comment by honzajavorek** [comment]
- existující říjnová Pyva a PyLadies
- PyCon 😱 (si asi zaslouží i svůj vlastní článek)
- Django Girls
- kurz @lspdv, pokud se rozjede ❗

**Comment by lspdv** [comment]
Jojo "jestli se rozjede" a "bude to punk" a tak dale a tak dale ;-)

Odesláno z iPadu
1. 9. 2016 v 20:28, Honza Javorek notifications@github.com:

**Comment by honzajavorek** [comment]
Vydáno v https://github.com/pyvec/blog.python.cz/pull/9
